import { ChainId } from "./chainId";
import { ChainSlug } from "./chainSlug";

export const ChainSlugToId = {
  [ChainSlug.ARBITRUM]: ChainId.ARBITRUM,
  [ChainSlug.ARBITRUM_GOERLI]: ChainId.ARBITRUM_GOERLI,
  [ChainSlug.ARBITRUM_SEPOLIA]: ChainId.ARBITRUM_SEPOLIA,
  [ChainSlug.OPTIMISM]: ChainId.OPTIMISM,
  [ChainSlug.OPTIMISM_GOERLI]: ChainId.OPTIMISM_GOERLI,
  [ChainSlug.OPTIMISM_SEPOLIA]: ChainId.OPTIMISM_SEPOLIA,
  [ChainSlug.BSC]: ChainId.BSC,
  [ChainSlug.BSC_TESTNET]: ChainId.BSC_TESTNET,
  [ChainSlug.MAINNET]: ChainId.MAINNET,
  [ChainSlug.GOERLI]: ChainId.GOERLI,
  [ChainSlug.SEPOLIA]: ChainId.SEPOLIA,
  [ChainSlug.POLYGON_MAINNET]: ChainId.POLYGON_MAINNET,
  [ChainSlug.POLYGON_MUMBAI]: ChainId.POLYGON_MUMBAI,
  [ChainSlug.AEVO_TESTNET]: ChainId.AEVO_TESTNET,
  [ChainSlug.AEVO]: ChainId.AEVO,
  [ChainSlug.HARDHAT]: ChainId.HARDHAT,
  [ChainSlug.AVALANCHE]: ChainId.AVALANCHE,
  [ChainSlug.LYRA_TESTNET]: ChainId.LYRA_TESTNET,
  [ChainSlug.LYRA]: ChainId.LYRA,
  [ChainSlug.XAI_TESTNET]: ChainId.XAI_TESTNET,
  [ChainSlug.SX_NETWORK_TESTNET]: ChainId.SX_NETWORK_TESTNET,
  [ChainSlug.SX_NETWORK]: ChainId.SX_NETWORK,
  [ChainSlug.MODE_TESTNET]: ChainId.MODE_TESTNET,
  [ChainSlug.VICTION_TESTNET]: ChainId.VICTION_TESTNET,
  [ChainSlug.CDK_TESTNET]: ChainId.CDK_TESTNET,
  [ChainSlug.BASE]: ChainId.BASE,
  [ChainSlug.MODE]: ChainId.MODE,
  [ChainSlug.ANCIENT8_TESTNET]: ChainId.ANCIENT8_TESTNET,
  [ChainSlug.ANCIENT8_TESTNET2]: ChainId.ANCIENT8_TESTNET2,
  [ChainSlug.HOOK_TESTNET]: ChainId.HOOK_TESTNET,
  [ChainSlug.HOOK]: ChainId.HOOK,
  [ChainSlug.PARALLEL]: ChainId.PARALLEL,
  [ChainSlug.MANTLE]: ChainId.MANTLE,
  [ChainSlug.REYA_CRONOS]: ChainId.REYA_CRONOS,
  [ChainSlug.REYA]: ChainId.REYA,
  [ChainSlug.SYNDR_SEPOLIA_L3]: ChainId.SYNDR_SEPOLIA_L3,
  [ChainSlug.POLYNOMIAL_TESTNET]: ChainId.POLYNOMIAL_TESTNET,
  [ChainSlug.KINTO]: ChainId.KINTO,
  [ChainSlug.KINTO_DEVNET]: ChainId.KINTO_DEVNET,
};
