import { ChainSlug } from "./chainSlug";

// chains having constant gas limits
export const ethLikeChains = [
  ChainSlug.MAINNET,
  ChainSlug.BSC,
  ChainSlug.POLYGON_MAINNET,
  ChainSlug.SEPOLIA,
  ChainSlug.SX_NETWORK,
  ChainSlug.SX_NETWORK_TESTNET,
  ChainSlug.ANCIENT8_TESTNET,
  ChainSlug.ANCIENT8_TESTNET2,
  ChainSlug.REYA_CRONOS,
  ChainSlug.REYA,
  ChainSlug.GOERLI,
  ChainSlug.VICTION_TESTNET,
  ChainSlug.SYNDR_SEPOLIA_L3,
  ChainSlug.BSC_TESTNET,
  ChainSlug.NEOX_TESTNET,
  ChainSlug.NEOX_T4_TESTNET,
  ChainSlug.NEOX,
  ChainSlug.GNOSIS,
  ChainSlug.LINEA,
  ChainSlug.ZKEVM,
  ChainSlug.AVALANCHE,
  ChainSlug.POLYGON_AMOY,
  ChainSlug.SONIC,
  ChainSlug.BERA,
  ChainSlug.MONAD_TESTNET,
  ChainSlug.SCROLL,
  ChainSlug.HYPEREVM,
];
