import { ChainSlug } from "./chainSlug";
import { HardhatChainName } from "./hardhatChainName";

export const hardhatChainNameToSlug = {
  [HardhatChainName.ARBITRUM]: ChainSlug.ARBITRUM,
  [HardhatChainName.ARBITRUM_GOERLI]: ChainSlug.ARBITRUM_GOERLI,
  [HardhatChainName.ARBITRUM_SEPOLIA]: ChainSlug.ARBITRUM_SEPOLIA,
  [HardhatChainName.OPTIMISM]: ChainSlug.OPTIMISM,
  [HardhatChainName.OPTIMISM_GOERLI]: ChainSlug.OPTIMISM_GOERLI,
  [HardhatChainName.OPTIMISM_SEPOLIA]: ChainSlug.OPTIMISM_SEPOLIA,
  [HardhatChainName.BSC]: ChainSlug.BSC,
  [HardhatChainName.MAINNET]: ChainSlug.MAINNET,
  [HardhatChainName.GOERLI]: ChainSlug.GOERLI,
  [HardhatChainName.SEPOLIA]: ChainSlug.SEPOLIA,
  [HardhatChainName.POLYGON_MAINNET]: ChainSlug.POLYGON_MAINNET,
  [HardhatChainName.AEVO_TESTNET]: ChainSlug.AEVO_TESTNET,
  [HardhatChainName.AEVO]: ChainSlug.AEVO,
  [HardhatChainName.HARDHAT]: ChainSlug.HARDHAT,
  [HardhatChainName.AVALANCHE]: ChainSlug.AVALANCHE,
  [HardhatChainName.LYRA_TESTNET]: ChainSlug.LYRA_TESTNET,
  [HardhatChainName.LYRA]: ChainSlug.LYRA,
  [HardhatChainName.XAI_TESTNET]: ChainSlug.XAI_TESTNET,
  [HardhatChainName.SX_NETWORK_TESTNET]: ChainSlug.SX_NETWORK_TESTNET,
  [HardhatChainName.SX_NETWORK]: ChainSlug.SX_NETWORK,
  [HardhatChainName.MODE_TESTNET]: ChainSlug.MODE_TESTNET,
  [HardhatChainName.VICTION_TESTNET]: ChainSlug.VICTION_TESTNET,
  [HardhatChainName.CDK_TESTNET]: ChainSlug.CDK_TESTNET,
  [HardhatChainName.BASE]: ChainSlug.BASE,
  [HardhatChainName.MODE]: ChainSlug.MODE,
  [HardhatChainName.ANCIENT8_TESTNET]: ChainSlug.ANCIENT8_TESTNET,
  [HardhatChainName.ANCIENT8_TESTNET2]: ChainSlug.ANCIENT8_TESTNET2,
  [HardhatChainName.HOOK_TESTNET]: ChainSlug.HOOK_TESTNET,
  [HardhatChainName.HOOK]: ChainSlug.HOOK,
  [HardhatChainName.PARALLEL]: ChainSlug.PARALLEL,
  [HardhatChainName.MANTLE]: ChainSlug.MANTLE,
  [HardhatChainName.REYA_CRONOS]: ChainSlug.REYA_CRONOS,
  [HardhatChainName.REYA]: ChainSlug.REYA,
  [HardhatChainName.SYNDR_SEPOLIA_L3]: ChainSlug.SYNDR_SEPOLIA_L3,
  [HardhatChainName.POLYNOMIAL_TESTNET]: ChainSlug.POLYNOMIAL_TESTNET,
  [HardhatChainName.BOB]: ChainSlug.BOB,
  [HardhatChainName.KINTO]: ChainSlug.KINTO,
  [HardhatChainName.KINTO_DEVNET]: ChainSlug.KINTO_DEVNET,
  [HardhatChainName.SIPHER_FUNKI_TESTNET]: ChainSlug.SIPHER_FUNKI_TESTNET,
  [HardhatChainName.WINR]: ChainSlug.WINR,
  [HardhatChainName.BLAST]: ChainSlug.BLAST,
  [HardhatChainName.BSC_TESTNET]: ChainSlug.BSC_TESTNET,
  [HardhatChainName.POLYNOMIAL]: ChainSlug.POLYNOMIAL,
  [HardhatChainName.SYNDR]: ChainSlug.SYNDR,
  [HardhatChainName.NEOX_TESTNET]: ChainSlug.NEOX_TESTNET,
  [HardhatChainName.NEOX_T4_TESTNET]: ChainSlug.NEOX_T4_TESTNET,
  [HardhatChainName.NEOX]: ChainSlug.NEOX,
};
