import { ChainSlug } from "./chainSlug";

export const MainnetIds: ChainSlug[] = [
  ChainSlug.MAINNET,
  ChainSlug.POLYGON_MAINNET,
  ChainSlug.ARBITRUM,
  ChainSlug.OPTIMISM,
  ChainSlug.BSC,
  ChainSlug.AEVO,
  ChainSlug.LYRA,
  ChainSlug.BASE,
  ChainSlug.MODE,
  ChainSlug.PARALLEL,
  ChainSlug.MANTLE,
  ChainSlug.REYA,
  ChainSlug.SX_NETWORK,
  ChainSlug.BOB,
  ChainSlug.KINTO,
  ChainSlug.WINR,
  ChainSlug.BLAST,
  ChainSlug.POLYNOMIAL,
  ChainSlug.SYNDR,
  ChainSlug.NEOX,
  ChainSlug.GNOSIS,
  ChainSlug.LINEA,
  ChainSlug.ZKEVM,
  ChainSlug.AVALANCHE,
  ChainSlug.XLAYER,
  ChainSlug.MANTA_PACIFIC,
];
