import { ChainSlug } from "./chainSlug";

export const opStackL2Chain = [
  ChainSlug.AEVO,
  ChainSlug.AEVO_TESTNET,
  ChainSlug.LYRA,
  ChainSlug.MODE_TESTNET,
  ChainSlug.LYRA_TESTNET,
  ChainSlug.MODE,
  ChainSlug.OPTIMISM,
  ChainSlug.OPTIMISM_SEPOLIA,
  ChainSlug.OPTIMISM_GOERLI,
  ChainSlug.BASE,
  ChainSlug.MANTLE,
  ChainSlug.POLYNOMIAL_TESTNET,
  ChainSlug.BOB,
  ChainSlug.SIPHER_FUNKI_TESTNET,
  ChainSlug.BLAST,
  ChainSlug.POLYNOMIAL,
  ChainSlug.MANTA_PACIFIC,
  ChainSlug.POLTER_TESTNET,
  ChainSlug.OPBNB,
  ChainSlug.ARENA_Z,
  ChainSlug.INK,
  ChainSlug.BASE_SEPOLIA,
  ChainSlug.B3,
];
