import { ChainSlug } from "./chainSlug";

export const TestnetIds: ChainSlug[] = [
  ChainSlug.GOERLI,
  ChainSlug.SEPOLIA,
  ChainSlug.ARBITRUM_GOERLI,
  ChainSlug.ARBITRUM_SEPOLIA,
  ChainSlug.OPTIMISM_GOERLI,
  ChainSlug.OPTIMISM_SEPOLIA,
  ChainSlug.AEVO_TESTNET,
  ChainSlug.LYRA_TESTNET,
  ChainSlug.XAI_TESTNET,
  ChainSlug.SX_NETWORK_TESTNET,
  ChainSlug.MODE_TESTNET,
  ChainSlug.VICTION_TESTNET,
  ChainSlug.CDK_TESTNET,
  ChainSlug.ANCIENT8_TESTNET,
  ChainSlug.ANCIENT8_TESTNET2,
  ChainSlug.HOOK_TESTNET,
  ChainSlug.REYA_CRONOS,
  ChainSlug.SYNDR_SEPOLIA_L3,
  ChainSlug.POLYNOMIAL_TESTNET,
  ChainSlug.KINTO_DEVNET,
  ChainSlug.SIPHER_FUNKI_TESTNET,
];
