import { ChainSlug } from "../../../src";

export const batcherSupportedChainSlugs = [
  ChainSlug.AEVO,
  ChainSlug.ARBITRUM,
  ChainSlug.OPTIMISM,
  ChainSlug.BSC,
  ChainSlug.POLYGON_MAINNET,
  ChainSlug.LYRA,
  ChainSlug.MAINNET,
  ChainSlug.MANTLE,
  ChainSlug.REYA,
  ChainSlug.AEVO_TESTNET,
  ChainSlug.SEPOLIA,
  ChainSlug.LYRA_TESTNET,
  ChainSlug.ARBITRUM_SEPOLIA,
  ChainSlug.OPTIMISM_SEPOLIA,
  // ChainSlug.MODE_TESTNET,
  ChainSlug.BASE,
  ChainSlug.MODE,
  ChainSlug.REYA_CRONOS,
  ChainSlug.BLAST,
  // ChainSlug.BSC_TESTNET,
  ChainSlug.GNOSIS,
  ChainSlug.LINEA,
  ChainSlug.ZKEVM,
  ChainSlug.AVALANCHE,
  // ChainSlug.XLAYER,
  // ChainSlug.MANTA_PACIFIC,
  // ChainSlug.ZKSYNC,
  ChainSlug.INK,
  ChainSlug.SONIC,
  // ChainSlug.BASE_SEPOLIA,
  ChainSlug.BERA,
  // ChainSlug.B3,
  ChainSlug.UNICHAIN,
  // ChainSlug.MONAD_TESTNET,
  ChainSlug.SCROLL,
  ChainSlug.SONEIUM,
  // ChainSlug.SWELLCHAIN,
  ChainSlug.WORLD_CHAIN,
  ChainSlug.PLUME,
  ChainSlug.KATANA,
  ChainSlug.HYPEREVM,
  ChainSlug.SEI,
  ChainSlug.PLASMA,
  ChainSlug.MONAD,
  ChainSlug.MEGAETH,
  ChainSlug.ETHEREAL,
  ChainSlug.RISE,
  ChainSlug.FLARE,
];