import { ChainSlug } from "../../../src";

export const batcherSupportedChainSlugs = [
  ChainSlug.AEVO,
  ChainSlug.ARBITRUM,
  ChainSlug.OPTIMISM,
  ChainSlug.BSC,
  ChainSlug.POLYGON_MAINNET,
  ChainSlug.LYRA,
  ChainSlug.MAINNET,
  ChainSlug.MANTLE,
  ChainSlug.REYA,
  // ChainSlug.SX_NETWORK,
  // ChainSlug.AEVO_TESTNET,
  ChainSlug.SEPOLIA,
  ChainSlug.LYRA_TESTNET,
  // ChainSlug.SX_NETWORK_TESTNET,
  ChainSlug.ARBITRUM_SEPOLIA,
  ChainSlug.OPTIMISM_SEPOLIA,
  // ChainSlug.MODE_TESTNET,
  ChainSlug.BASE,
  ChainSlug.MODE,
  ChainSlug.REYA_CRONOS,
  ChainSlug.SYNDR_SEPOLIA_L3,
  ChainSlug.POLYNOMIAL_TESTNET,
  // ChainSlug.BOB,
  ChainSlug.KINTO,
  // ChainSlug.KINTO_DEVNET,
  // ChainSlug.SIPHER_FUNKI_TESTNET,
  ChainSlug.WINR,
  ChainSlug.BLAST,
  // ChainSlug.BSC_TESTNET,
  ChainSlug.POLYNOMIAL,
  ChainSlug.SYNDR,
  // ChainSlug.NEOX_TESTNET,
  // ChainSlug.NEOX_T4_TESTNET,
  ChainSlug.NEOX,
  ChainSlug.GNOSIS,
  ChainSlug.LINEA,
  ChainSlug.ZKEVM,
  ChainSlug.AVALANCHE,
  // ChainSlug.XLAYER,
  // ChainSlug.MANTA_PACIFIC,
  // ChainSlug.POLTER_TESTNET,
  ChainSlug.POLYGON_AMOY,
  ChainSlug.OPBNB,
  ChainSlug.GEIST,
  // ChainSlug.ZERO_SEPOLIA,
  ChainSlug.ZERO,
  ChainSlug.ZKSYNC,
  ChainSlug.ARENA_Z,
  ChainSlug.INK,
  ChainSlug.SONIC,
  // ChainSlug.BASE_SEPOLIA,
  ChainSlug.BERA,
  ChainSlug.B3,
  ChainSlug.UNICHAIN,
  // ChainSlug.MONAD_TESTNET,
  ChainSlug.SCROLL,
  ChainSlug.SONEIUM,
];
