import { ChainSlug } from "../../../src";

export const batcherSupportedChainSlugs = [
  ChainSlug.AEVO,
  ChainSlug.ARBITRUM,
  ChainSlug.OPTIMISM,
  ChainSlug.BSC,
  ChainSlug.POLYGON_MAINNET,
  ChainSlug.LYRA,
  ChainSlug.MAINNET,
  ChainSlug.MANTLE,
  ChainSlug.HOOK,
  ChainSlug.REYA,
  // ChainSlug.SX_NETWORK,
  ChainSlug.AEVO_TESTNET,
  ChainSlug.SEPOLIA,
  ChainSlug.LYRA_TESTNET,
  // ChainSlug.SX_NETWORK_TESTNET,
  ChainSlug.ARBITRUM_SEPOLIA,
  ChainSlug.OPTIMISM_SEPOLIA,
  // ChainSlug.MODE_TESTNET,
  ChainSlug.BASE,
  ChainSlug.MODE,
  // ChainSlug.ANCIENT8_TESTNET2,
  ChainSlug.HOOK_TESTNET,
  ChainSlug.REYA_CRONOS,
  ChainSlug.SYNDR_SEPOLIA_L3,
  ChainSlug.POLYNOMIAL_TESTNET,
  ChainSlug.BOB,
  ChainSlug.KINTO,
  ChainSlug.KINTO_DEVNET,
  ChainSlug.SIPHER_FUNKI_TESTNET,
  ChainSlug.WINR,
  ChainSlug.BLAST,
];
