import { ChainSlug } from "../../../src";

export const confirmations = {
  [ChainSlug.AEVO]: 2,
  [ChainSlug.ARBITRUM]: 1,
  [ChainSlug.LYRA]: 2,
  [ChainSlug.OPTIMISM]: 15,
  [ChainSlug.BSC]: 1,
  [ChainSlug.POLYGON_MAINNET]: 256,
  [ChainSlug.MAINNET]: 18,
  [ChainSlug.BASE]: 1,
  [ChainSlug.MODE]: 2,
  [ChainSlug.ARBITRUM_GOERLI]: 1,
  [ChainSlug.AEVO_TESTNET]: 1,
  [ChainSlug.LYRA_TESTNET]: 1,
  [ChainSlug.OPTIMISM_GOERLI]: 1,
  [ChainSlug.GOERLI]: 1,
  [ChainSlug.XAI_TESTNET]: 1,
  [ChainSlug.SX_NETWORK_TESTNET]: 1,
  [ChainSlug.SX_NETWORK]: 1,
  [ChainSlug.MODE_TESTNET]: 1,
  [ChainSlug.VICTION_TESTNET]: 1,
  [ChainSlug.CDK_TESTNET]: 1,
  [ChainSlug.ARBITRUM_SEPOLIA]: 1,
  [ChainSlug.OPTIMISM_SEPOLIA]: 1,
  [ChainSlug.SEPOLIA]: 1,
  [ChainSlug.ANCIENT8_TESTNET]: 1,
  [ChainSlug.ANCIENT8_TESTNET2]: 1,
  [ChainSlug.HOOK_TESTNET]: 1,
  [ChainSlug.HOOK]: 1,
  [ChainSlug.PARALLEL]: 1,
  [ChainSlug.MANTLE]: 1,
  [ChainSlug.REYA_CRONOS]: 1,
  [ChainSlug.REYA]: 0,
  [ChainSlug.SYNDR_SEPOLIA_L3]: 1,
  [ChainSlug.POLYNOMIAL_TESTNET]: 1,
  [ChainSlug.BOB]: 0,
  [ChainSlug.KINTO]: 0,
  [ChainSlug.KINTO_DEVNET]: 0,
  [ChainSlug.SIPHER_FUNKI_TESTNET]: 0,
  [ChainSlug.WINR]: 0,
  [ChainSlug.BLAST]: 0,
  [ChainSlug.BSC_TESTNET]: 1,
  [ChainSlug.POLYNOMIAL]: 1,
};
