import { ChainSlug } from "../../../src";

export const explorers = {
  [ChainSlug.AEVO]: "https://explorer.aevo.xyz",
  [ChainSlug.LYRA]: "https://explorer.lyra.finance",
  [ChainSlug.MANTLE]: "https://explorer.mantle.xyz",
  [ChainSlug.REYA]: "https://explorer.reya.network",
  [ChainSlug.SIPHER_FUNKI_TESTNET]: "https://sepolia-sandbox.funkichain.com",
  [ChainSlug.WINR]: "https://explorerl2new-winr-mainnet-0.t.conduit.xyz",
  [ChainSlug.BLAST]: "https://blastscan.io",
  [ChainSlug.BSC_TESTNET]: "https://testnet.bscscan.com/",
  [ChainSlug.POLYNOMIAL]: "https://explorer.polynomial.fi",
  [ChainSlug.SYNDR]: "https://explorer.syndr.com/",
  [ChainSlug.NEOX_TESTNET]: "https://xt3scan.ngd.network/",
  [ChainSlug.NEOX_T4_TESTNET]: "https://xt4scan.ngd.network/",
  [ChainSlug.NEOX]: "https://xexplorer.neo.org",
  [ChainSlug.GNOSIS]: "https://gnosisscan.io/",
  [ChainSlug.LINEA]: "https://lineascan.build/",
  [ChainSlug.ZKEVM]: "https://zkevm.polygonscan.com/",
  [ChainSlug.AVALANCHE]: "https://snowtrace.io/",
  [ChainSlug.XLAYER]: "https://www.okx.com/web3/explorer/xlayer",
  [ChainSlug.MANTA_PACIFIC]: "https://pacific-explorer.manta.network/",
  [ChainSlug.POLTER_TESTNET]: "https://polter-testnet.explorer.alchemy.com/",
  [ChainSlug.POLYGON_AMOY]: "https://amoy.polygonscan.com/",
  [ChainSlug.OPBNB]: "https://opbnb.bscscan.com/",
  [ChainSlug.GEIST]: "https://geist-mainnet.explorer.alchemy.com/",
  [ChainSlug.ZERO_SEPOLIA]: "https://explorer.zero.network/",
  [ChainSlug.ZERO]: "https://zerion-explorer.vercel.app/",
  [ChainSlug.ZKSYNC]: "https://explorer.zksync.io/",
  [ChainSlug.ARENA_Z]: "https://explorer.arena-z.gg/",
  [ChainSlug.INK]: "https://explorer.inkonchain.com/",
  [ChainSlug.SONIC]: "https://sonicscan.org/",
  [ChainSlug.BASE_SEPOLIA]: "https://sepolia.basescan.org/",
  [ChainSlug.BERA]: "https://berascan.com/",
  [ChainSlug.B3]: "https://explorer.b3.fun/",
  [ChainSlug.UNICHAIN]: "https://unichain.blockscout.com/",
  [ChainSlug.MONAD_TESTNET]: "https://monad-testnet.socialscan.io/",
  [ChainSlug.SCROLL]: "https://scrollscan.com/",
  [ChainSlug.SONEIUM]: "https://soneium.blockscout.com/",
  [ChainSlug.SWELLCHAIN]: "https://explorer.swellnetwork.io/",
};
