import { ChainSlug } from "../../../src";

export const icons = {
  [ChainSlug.AEVO]: "https://media.socket.tech/aevo.png",
  [ChainSlug.LYRA]: "https://media.socket.tech/lyra.png",
  [ChainSlug.MANTLE]: "https://media.socket.tech/mantle.png",
  [ChainSlug.REYA]: "https://media.socket.tech/reya.png",
  [ChainSlug.BSC_TESTNET]:
    "https://testnet.bscscan.com/assets/bsc/images/svg/logos/logo-light.svg?v=24.5.5.0",
  [ChainSlug.POLYNOMIAL]: "",
  [ChainSlug.SYNDR]: "",
  [ChainSlug.NEOX_TESTNET]: "",
  [ChainSlug.NEOX_T4_TESTNET]: "",
  [ChainSlug.NEOX]: "",
  [ChainSlug.GNOSIS]: "",
  [ChainSlug.LINEA]: "",
  [ChainSlug.ZKEVM]: "",
  [ChainSlug.AVALANCHE]: "",
  [ChainSlug.XLAYER]: "",
  [ChainSlug.MANTA_PACIFIC]: "",
  [ChainSlug.POLTER_TESTNET]: "",
  [ChainSlug.POLYGON_AMOY]: "",
  [ChainSlug.OPBNB]: "",
  [ChainSlug.GEIST]: "",
  [ChainSlug.ZERO_SEPOLIA]: "",
  [ChainSlug.ZERO]: "",
  [ChainSlug.ZKSYNC]: "",
  [ChainSlug.ARENA_Z]: "",
  [ChainSlug.INK]: "",
  [ChainSlug.SONIC]: "",
  [ChainSlug.BASE_SEPOLIA]: "",
  [ChainSlug.BERA]: "",
  [ChainSlug.B3]: "",
  [ChainSlug.UNICHAIN]: "",
  [ChainSlug.MONAD_TESTNET]: "",
  [ChainSlug.SCROLL]: "",
  [ChainSlug.SONEIUM]: "",
  [ChainSlug.SWELLCHAIN]: "",
  [ChainSlug.WORLD_CHAIN]: "",
  [ChainSlug.PLUME]: "",
  [ChainSlug.KATANA]: "",
  [ChainSlug.HYPEREVM]: "",
};
